[package]
name = "redical"
version = "0.1.0"
edition = "2021"

[lib]
name = "reidcal"
crate-type = ["cdylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis-module = "1.0.1"
bincode = "1.3.3"
serde = { version = "1.0.162", features = ["derive"] }
libc = "0.2"
