---

name: Build Docker image for latest tag release and push to Dockerhub.

on:
  # This workflow is run each time a tag is pushed.
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  DOCKER_ORG: gregjoy
  DOCKER_REPO: redical

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up buildx
        uses: docker/setup-buildx-action@v2

      - name: dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{env.DOCKER_ORG}}/${{env.DOCKER_REPO}}:${{github.ref_name}}

      - name: Update readme and description
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASS: ${{secrets.DOCKERHUB_PASSWORD}}
        with:
          destination_container_repo: ${{env.DOCKER_ORG}}/${{env.DOCKER_REPO}}
          provider: dockerhub
          short_description: 'A Redis module that facilitates the storage, expansion, and querying of overridable calendar events.'
          readme_file: 'README.md'
